import Link from "next/link";
import { LegalDocument } from "@/components/legal-document";

export const metadata = { title: "Terms of Service | CertiBlank", description: "Terms for using CertiBlank’s free certification practice service." };

export default function TermsPage() {
  return <LegalDocument title="Terms of Service" description="The ground rules for using CertiBlank, keeping accounts safe, and learning responsibly." sections={[
    { id: "service", title: "The service and operator", content: <><p>CertiBlank is an independent certification practice service operated by Wael Demeri in Jordan. These terms govern use of the hosted service at certiblank.com. Please read them before using it. If you do not agree, do not use the service. Questions can be sent to <a href="mailto:waeldemeri@gmail.com">waeldemeri@gmail.com</a>.</p><p>The service is currently free. Any future paid offering will have its price and terms explained before you choose to purchase it; using the current free service does not authorize a future charge.</p></> },
    { id: "eligibility", title: "Age and eligibility", content: <p>You must be at least 13 to use CertiBlank. If you have not reached the age at which you can legally agree to these terms or provide the required data-processing consent where you live, a parent or guardian must be involved and provide any legally required permission. Being 13 does not automatically mean you have that legal capacity.</p> },
    { id: "accounts", title: "Accounts and guest practice", content: <><p>You may practice without an account. If you create one, provide accurate information, protect your login credentials, and tell us if you suspect unauthorized access. Do not impersonate someone else or use another person’s account without authorization.</p><p>Guest progress depends on browser identifiers and storage. Clearing storage, changing devices, or losing access to your browser may prevent recovery. Signing in can associate eligible guest attempts with your account. We work to save progress reliably, but interrupted connections and technical failures can affect it.</p></> },
    { id: "practice", title: "Practice, not official certification", content: <><p>Questions, explanations, and exam configurations are learning aids and may contain errors or become outdated. Practice scores are estimates, not official vendor psychometric scores. Results do not guarantee that you will pass an exam, obtain a qualification, or meet a professional requirement. Check the vendor’s current exam guidance and official documentation.</p><p>CertiBlank does not issue vendor certifications and is not endorsed by or affiliated with AWS, Microsoft, Cisco, Google, GitHub, or other vendors merely because their names, materials, or sign-in services appear here.</p></> },
    { id: "acceptable-use", title: "Acceptable use", content: <ul><li>Use the service lawfully and respect other people’s privacy and intellectual property.</li><li>Do not bypass authentication, access another person’s data, evade rate limits, send spam, or deliberately overload or damage the service.</li><li>Do not submit secrets, confidential exam questions, stolen materials, or malicious content through requests or support messages.</li><li>Report suspected vulnerabilities privately using the repository’s security reporting instructions or our contact email. Open-source access is not permission to attack the hosted service.</li></ul> },
    { id: "content", title: "Content and open-source code", content: <><p>The application source code is available under the MIT license included in its repository. These service terms do not remove rights granted by that license. Vendor names, logos, certification marks, and other third-party materials remain subject to their owners’ rights; the code license does not grant rights to those assets.</p><p>You retain rights to content you submit and allow us to use it as needed to handle your request or feedback. A certification request is a suggestion, not a promise to publish a question bank or meet a deadline.</p></> },
    { id: "privacy", title: "Privacy", content: <p>Our <Link href="/privacy">Privacy Policy</Link> explains account data, practice history, functional cookies, service providers, and how to request access or deletion. Agreeing to these terms does not replace any separate consent required for personal-data processing.</p> },
    { id: "availability", title: "Availability and account restrictions", content: <p>Features and content may change, and maintenance or outages can interrupt access. We may restrict access when reasonably necessary to address abuse, a security risk, a legal requirement, or a serious breach of these terms. Where practical, we will explain the restriction and allow you to contact us about it. You can stop using the service at any time and contact us to request account deletion.</p> },
    { id: "liability", title: "Responsibility and limitations", content: <p>To the extent permitted by applicable law, the service is provided as available, without a guarantee of uninterrupted operation, complete accuracy, or a particular learning outcome. We are not responsible for exam results or losses caused by reliance on practice content to the extent the law permits that limitation. Nothing here excludes responsibility that cannot lawfully be excluded, including applicable consumer rights or liability for fraud or intentional misconduct.</p> },
    { id: "law-and-changes", title: "Law, changes, and contact", content: <><p>These terms are governed by the laws of Jordan, subject to any mandatory rights and protections that apply where you live. This does not require you to waive protections or complaint routes that cannot legally be waived.</p><p>We will publish updated terms with a revised date and provide reasonable notice of material changes through the service. Where renewed agreement is required, we will request it. For support or concerns, contact <a href="mailto:waeldemeri@gmail.com">waeldemeri@gmail.com</a>.</p></> },
  ]} />;
}
